### PR TITLE
adding the search parameters of an a-tag href attribute

### PR DESCRIPTION
**Pull request by elgubenis**

### CODE REVIEW

**Comment by jmeas** [comment]
lgtm. Thanks @elgubenis !

I'm going to add a unit test, then I'll cut a release tonight.

**Comment by elgubenis** [comment]
i already wrote a test, but i dont know how to include it :disappointed: 

```javascript
describe('the link has search parameters', function() {
      beforeEach(function() {
        var $link = $('<a href="path/to/my-thing?page=1&limit=50"></a>');
        this.setFixtures($link);
        this.sinon.stub(Backbone.Intercept, 'navigate');
        $link.trigger(this.leftClick);
      });

      it('should intercept the link', function() {
        expect(this.leftClick.preventDefault).to.have.been.calledOnce;
      });

      it('should have the search parameters inside the link navigated to', function() {
        expect(Backbone.Intercept.navigate)
          .to.have.been.calledOnce
          .and.calledWithExactly('test/path/to/my-thing?page=1&limit=50', {trigger:true});
      });
    });
```

**Comment by elgubenis** [comment]
and i dont know if its the way you want a test to be written tbh :disappointed:

**Comment by jmeas** [comment]
Looks good to me @elgubenis ! The test directory is [here](https://github.com/jmeas/backbone.intercept/tree/master/test/unit).

**Pull request merged**
